### ISSUE TITLE
How to run a sample code?

### ISSUE THREAD

**Issue by purvaten** [s-trinh/Chamfer-Matching#1]
Can you please provide the steps for running an example of Chamfer matching like the one mentioned in the README?

**Comment by s-trinh** [comment]
Have a look at this file: [test-chamfer-matching.cpp](https://github.com/s-trinh/Chamfer-Matching/blob/master/test/test-chamfer-matching.cpp).

**Comment by purvaten** [comment]
I am having some problems compiling the code. Here's what I have done so far-

1. git clone https://github.com/s-trinh/Chamfer-Matching.git
2. cd Chamfer-Matching-master
3. mkdir build
4. cd build
5. cmake ../ -DCMAKE_CURRENT_SOURCE_DIR="/path/to/Chamfer-Matching-master/" -DOpenCV_DIR="/path/to/directory/containing/OpenCVConfig.cmake/" -DCMAKE_CXX_FLAGS="-std=c++11"
6. make

cmake runs fine. On running make I get the following error while linking-
> Linking CXX executable test-contours-orientation
> /usr/bin/ld: cannot find -lstd=c++11

**NOTE** - I had to make changes to the some of the files in the test folders to include appropriate header files from opencv, possibly due to some changes in the latest opencv version. FYI I am using opencv version 4.0.0

**Comment by s-trinh** [comment]
Unfortunately, I will not be able to test if everything builds fine with OpenCV 4 and I have not used this code since a long time.

Some options:

- switch to OpenCV 3.4 branch that does not require C++11?
- clean the build directory and redo the procedure? You can also try with `ccmake` to have a "GUI"
- which `gcc` version do you have? See for instance this [answer](https://stackoverflow.com/questions/10851247/how-to-activate-c-11-in-cmake/25836953#25836953).
- what OS are you using?
- add directly `add_compile_options(-std=c++11)` in the `CMakeLists.txt`?
- maybe try to build a simple project with C++11 code (just add `auto i = 0` in a main) to see if everything is ok?

**Comment by s-trinh** [comment]
I have pushed some fix to be able to build with OpenCV 4.
I have managed to run `test-chamfer-matching`. 
```
gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
You can also check that `OpenCV_DIR` is correctly set with `ccmake`.
My `ccmake` with `-std=c++11`:

![image](https://user-images.githubusercontent.com/8035162/49640982-3aa2c780-fa0f-11e8-8da3-d253097fe9c6.png)
